spring:
  application:  
    name: eureka-basic-provider
  zipkin:
    base-url: http://localhost:8781
    
server:
  port: 8281

eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka1:8181/eureka,http://eureka2:8182/eureka
