spring:
  application:  
    name: zuul-gateway
    
server:
  port: 8481

eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka1:8181/eureka,http://eureka2:8182/eureka

      
#zuul router
#1 url key words matching
zuul:
  ignored-services: eureka-basic-provider
  routes:
    route1:
      path: /route1/**
      url: http://localhost:8281/     