spring:
  application:  
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/scsimonxchen/spring-cloud-lab-config
          #username:
          #password:
    
server:
  port: 8581

eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka1:8181/eureka,http://eureka2:8182/eureka
