spring:
  application:  
    name: eureka-server
    
server:
  port: 8180

eureka:
  client:
    #是否将自己注册到eureka-server 默认为true
    registerWithEureka: false
    #是否从eureka-server获取注册信息，默认为true
    fetchRegistry: false

