spring:
  application:  
    name: eureka-basic-consumer
  zipkin:
    base-url: http://localhost:8781
    
server:
  port: 8381

eureka:
  client:
    serviceUrl: 
      defaultZone: http://eureka1:8181/eureka,http://eureka2:8182/eureka

      